### ISSUE TITLE
parse exceptions thrown on actual pixels

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-pixeltracker#10]
Noticed in production logs today, in a [customer flow](https://next.leadconduit.com/flows/5591998ffd7afa4c397417bf/) that uses this integration and gets back an `image/gif` type response, that a parse error is thrown (see below). The outcome is still success, but this integration should be fixed to better handle this.

```
[2016-04-15T19:57:28.037Z]  WARN: lc-handler/11009 on orcrist.local: Error in handle function (rid=5668, module=steps/recipient, flowId=5418bcd3ac3e980daffc46eb, entity_id=5668b48fab4461516fa66637, step=2, entity="Pixel Tracker", integration=leadconduit-pixeltracker.outbound)
    err: Error: Parse Error
      at Error (native)
      at Socket.socketOnData (_http_client.js:305:20)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at InternalSocket.onread (net.js:523:20)
      at InternalSocket.readData (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/mitm/lib/internal_socket.js:41:13)
      at emitOne (events.js:77:13)
      at InternalSocket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at InternalSocket.Readable.push (_stream_readable.js:110:10)
      at InternalSocket._write (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/mitm/lib/internal_socket.js:65:15)
      at doWrite (_stream_writable.js:292:12)
      at writeOrBuffer (_stream_writable.js:278:5)
      at InternalSocket.Writable.write (_stream_writable.js:207:11)
      at InternalSocket.writeUtf8String (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/mitm/lib/internal_socket.js:84:8)
      at createWriteReq (net.js:707:21)
      at Socket._writeGeneric (net.js:671:11)
      at Socket._write (net.js:694:8)
      at doWrite (_stream_writable.js:292:12)
      at clearBuffer (_stream_writable.js:396:7)
      at Socket.Writable.uncork (_stream_writable.js:230:7)
      at ServerResponse.OutgoingMessage.end (_http_outgoing.js:589:21)
      at respond (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/lib/intercept.js:69:16)
      at IncomingMessage.<anonymous> (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/lib/intercept.js:55:14)
      at IncomingMessage.<anonymous> (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/continuation-local-storage/context.js:76:17)
      at emitNone (events.js:67:13)
      at IncomingMessage.emit (events.js:166:7)
      at IncomingMessage.emitted [as emit] (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
      at endReadableNT (_stream_readable.js:903:12)
      at /Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
      at doNTCallback2 (node.js:439:9)
      at process._tickDomainCallback (node.js:394:17)
      at process.<anonymous> (/Users/cgrayson/ap/src/leadconduit-app/node_modules/@activeprospect/request-capture/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
```

From a lead: 
## Request

```
GET http://o1.email.customer.com/public/?q=direct_add&fn=Public_DirectAddForm&id=anoxxzzvsdjlihnhkxwvedzpdjpgbcp&email=test@yahoo.com&list1=0bca03ec000000000000000000000004ac28&list2=584e057e-9e64-41b1-a146-64c465a187ef&field1=site_source,set,PD2840&field2=firstname,set,test&field3=lastname,set,test HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded
Host: o1.email.customer.com
Connection: keep-alive
```
## Response

```
HTTP/1.1 200 OK
Date: Fri, 15 Apr 2016 20:01:39 GMT
Server: Apache
Vary: Accept-Encoding
Content-Length: 43
X-Cnection: close
Content-Type: image/gif

GIF89a����!�,D;
```

**Comment by alexkwolfe** [comment]
There's also n open issue for this in the request-capture repo

**Comment by cgrayson** [comment]
Ah. [This one](https://github.com/activeprospect/request-capture/issues/1).
